---
layout: cv
title: Elie Mambou's CV
---
# Elie S Mambou
Multilanguage Translation Manager, Full Stack Developer.

<div id="webaddress">
<a href="mam13003@byui.edu">mam13003@byui.edu</a>
| <a href="http://linkedin.com/in/eliesilveremambou">My linkedin page</a>
</div>


## Currently

Working for The Africa South Area, Church of Jesus Christ of latter-day Saints

### Specialized in

Training, developing capabilities among team members, Coordinating resolutions of issues, and balancing priorities.

### Languages Spoken

English, French, German, Spanish and Portuguese.


### Experience

`May 2020 - Present`
Multilanguage Translation Manager, May 2020 - Present

`January 20213 - Aprl 2020`
Senior Accountant, January 2013 - April 2020

## Education

`1987 - 1992`
__Rural Institute of Development__

`1993 - 1995`
__Faculty of Economic Science__

`2014 - 2019`
__Brigham Young University Idaho, Rexburg USA,__
_Bachelor of Science, Business Management, emphasis - Finance_

_Writing and Reasoning foundations;_
_Marketing Management;_
_Entrepreneurial Management;_
_Organizational Effectiveness;_
_Business & Leadership skills;_
_Business Statistics;_
_Production & Operation Management;_
_Commercial Fundamentals;_
_Financial and Managerial Accounting_


`2021 - 2024`
__Brigham Young University Idaho, Rexburg USA,__
_Bachelor of Science, Applied Technology, emphasis - Web Development_

_Create dynamic webpages adhering to industry standards and best practices;_
_Continuously acquire and implement new technologies and programming technique;_
_Demonstrate well-developed problem-solving skills;_
_Utilize Object-Oriented Programming principles;_
_Demonstrate the ability to design and develop effective online solutions using current web technologies;_
_Develop programs to achieve meaningful tasks across diverse domains_


## Skills
_CSS, HTML, JavaScript, Python & SQL_
_Proficient in Excel and Microsoft Office,_
_Presentation Skills,_
_Teamwork and Collaboration,_
_Conflict Resolution & Problem solving,_
_Communication & Organization_


## Hobbies
Soccer, Reading, Gardening


<!-- ### Footer

Last updated: July 2024 -->